language: python
python:
 - 2.6
 - 2.7

env:
 - DJANGO_VERSION=1.4.17
 - DJANGO_VERSION=1.5.12
 - DJANGO_VERSION=1.6.9
 - DJANGO_VERSION=1.7.2

matrix:
  exclude:
  - python: 2.6
    env: DJANGO_VERSION=1.7.2

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install . --use-mirrors

script: python setup.py test
